import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
//输入http://localhost:3000/sell-nft 就可以访问到该页面
export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            Sell page
        </div>
    )
}
